### ISSUE TITLE
Getting the below issue when Skylight is being loaded.

### ISSUE THREAD

**Issue by harshabhat86** [marcio/react-skylight#10]
```
react-skylight/src/skylight.jsx Line 72: Unexpected token <
You may need an appropriate loader to handle this file type.
| 
|         if (this.props.showOverlay) {
|             overlay = (<div style={overlayStyles}></div>);
|         }
| 
 @ ./~/react-skylight/index.js 1:17-46
```

**Comment by bebraw** [comment]
@marcio Probably the cleanest way to solve this would be to generate a vanilla version for dist. You can do this as follows:

1. Set up `"prepublish": "babel ./src --out-dir ./dist-modules"` at `package.json` scripts section
2. Include `index.js` there as an entry point
3. Let `package.json` main point at the generated entry point - `"main": "dist-modules/index.js",`

You also need to hit `npm i babel --save-dev` to include it into your project.

**Comment by marcio** [comment]
@harshabhat86, I think so this is something about your jsx compiler. what are you using to handle your .jsx files?

**Comment by marcio** [comment]
@bebraw good idea. thks.

**Comment by christianidylle** [comment]
@marcio Unfortunately this component is unusable for the most part until @bebraw suggestions are implemented.

**Comment by marcio** [comment]
Hi @christianidylle! I agree, but for now, I'm very busy. Your pull request will be appreciated! :wink:
