### ISSUE TITLE
.jsx source, problems with mocha

### ISSUE THREAD

**Issue by tugend** [marcio/react-skylight#11]
Hi, I think your module is really neat. Nice job there. ^_^

But, would you mind offering a non-jsx source too?
I'm using browserify and mocha and preprocessed jsx is fine
when used in an app, but the preprocesser is not run when 
files are piped mocha/node instead - I really don't want to keep a
compiled version of the module and update it whenever I 
update from npm. =/

I'm also curious as to why you'd decide to force users to 
compile jsx when using the Skylight?

**Comment by bebraw** [comment]
@tugend See #10. I think it's on @marcio's todo. It's not a big change to make really.
