### ISSUE TITLE
skylight won't hide when "onClick" initiated from a div or img

### ISSUE THREAD

**Issue by Zone-Ghost** [marcio/react-skylight#13]
I'm only able to get the hide() option to work when the skylight show()'s from a button.  If any other event generates the skylight, the this.hide() function loses track.  I can put an image and button side-by-side with the same onClick={foo.hide()} and the button will open, with the X in the corner closing it, while the image when clicked will pop the same skylight component up, but the X doesn't work.  

Am I missing something?

**Comment by tstibbs** [comment]
I'm having this issue too, I'd like to know why this issue is closed? If it's not a supported use of the component (and therefore not a bug), could this issue be reopened as a feature request? Or @Zone-Ghost if you found a solution could you share it please?

**Comment by marcio** [comment]
Hi @tstibbs, this issue is closed because I cannot reproduce this behavior.

Please, show me your code.

**Comment by tstibbs** [comment]
The code that uses skylight looks like this: https://gist.github.com/tstibbs/17b7beb2685fcfedaa1d0368cf2f8024#file-hello-js

I've reproduced this in very simple project based off [react-quickstart](https://github.com/mrblueblue/react-quickstart) (which therefore using babel and webpack if it's relevant) - which I can upload somewhere if required.

**Comment by marcio** [comment]
Thanks for the example.

Yes, there is a problem or a "strange behavior", it happens when you put <SkyLight> inside a div that is firing the event. I will investigate the root cause.

You can refactor your code to use SkyLight outside the div that is firing the event, this works nicely.

```jsx
<div>
  <div onClick={() => this.refs.buildsPopup.show()}>
    <p>blah</p>
   </div>
   <SkyLight hideOnOverlayClicked ref="buildsPopup">
     <p>more blah</p>
   </SkyLight>
</div>
```

**Comment by tstibbs** [comment]
Perfect, thanks! I'm struggling to think of a case where that workaround wouldn't be sufficient, so perhaps this issue isn't a big deal after all.
