### ISSUE TITLE
PeerDep Problem

### ISSUE THREAD

**Issue by yhjor1212** [marcio/react-skylight#16]
Hi, I encounter the following problem when installing:

georgejor$ npm install --save react-skylight
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/georgejor/.nvm/versions/node/v0.12.5/bin/node" "/Users/georgejor/.nvm/versions/node/v0.12.5/bin/npm" "install" "--save" "react-skylight"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package object-assign does not satisfy its siblings' peerDependencies requirements!

Please help! Thanks!

**Comment by bebraw** [comment]
Can you understand where that `object-assign` dependency comes from? It doesn't look like `react-skylight` depends on it directly. Do you have some packages installed in your project already?
