### ISSUE TITLE
Error thrown on mounting

### ISSUE THREAD

**Issue by MikaelLarsson** [marcio/react-skylight#21]
All of a sudden there is an error thrown when SkyLight is mounted, saying "Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined". 

It used to work, it might have broke after i updated npm. Any ideas what could be wrong?

**Comment by marcio** [comment]
Hi @MikaelLarsson what react version are you using?

**Comment by MikaelLarsson** [comment]
0.13.0

**Comment by MikaelLarsson** [comment]
The error is thrown in /react/lib/ReactElementValidator line 355

**Comment by MikaelLarsson** [comment]
It seemed that it was related to an entire different issue: https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375
