### ISSUE TITLE
Produces error 'Unexpected token' on using some CSS properties. 

### ISSUE THREAD

**Issue by purezen** [marcio/react-skylight#25]
I am using the boilerplate https://github.com/juliancwirko/react-boilerplate, and tried applying some properties on a modal using...
```
var improvedObjectiveModal = {
        backgroundColor: '#00897B',
        color: '#ffffff',
        width: '50%',
        height: '100px',
        display: 'flex',
        align-items: 'center',
        justify-content: 'center'
      };
```
But my app produces the error for properties like ```align-items``` and ```justify-content```. The other properties are otherwise working as expected.

**Comment by marcio** [comment]
Hi, 

Probably it's not an error in react-skylight, looks that something in your object improvedObjectiveModal.
Try change the keys align-items and justify-content to alignItems and justifyContent.

I hope it works.

**Comment by purezen** [comment]
ah yes, that worked!
