### ISSUE TITLE
How to get access to element inside Modal?

### ISSUE THREAD

**Issue by purezen** [marcio/react-skylight#27]
Hi,
I have been trying to implement autofocus on a text input field inside a modal. I started by calling `focus()` on the element inside the `_executeAfterModalOpen()` callback. An alert function inside the callback is working fine.
But it looks like `this` inside the callback is not pointing to the component. So, `this.refs` is showing up as `_unassigned_` which I am trying to use to get hold of the input field in turn doing `this.refs.modal.focus()`.

**Comment by marcio** [comment]
Hi, maybe this example help you.

```js 

_executeAfterModalOpen(){
    this.refs.myInput.focus();
}

<SkyLight afterOpen={this._executeAfterModalOpen}><input ref='myInput' type='text' /></SkyLight>

```

Please, let me know if that works :+1:

**Comment by purezen** [comment]
Well, that's what I have been trying. But still doesn't work.

**Comment by purezen** [comment]
Hey, can you confirm if that is working? Coz, for me `this` inside _executeAfterModelOpen() is pointing to something else.
```
Object { 
  hideOnOverlayClicked: true, 
  afterOpen: wrapMethod/<(),
  dialogStyles: Object,
  title: "Improve task", 
  children: Object,
  showOverlay: true,
  overlayStyles: Object,
  closeButtonStyle: Object
}
```
