### ISSUE TITLE
No information that react-skylight is available only on es2015.

### ISSUE THREAD

**Issue by skatpgusskat** [marcio/react-skylight#29]
@marcio Could you remind us that we should use ```import SkyLight from 'react-skylight'``` instead ``` SkyLight = require('react-skylight')``` in READMD.md?
Because not everyone use es2015. at least I think you should have to explain that react-skylight 3.0 is on es2015 only.

**Comment by marcio** [comment]
@skatpgusskat I tested react-skylight v0.3.0 only in es2015.
