### ISSUE TITLE
Is it possible to add open/close transitions?

### ISSUE THREAD

**Issue by Ajar-Ajar** [marcio/react-skylight#34]
Hi there,
I'm looking for a modal component, yours looks great in terms of functionality.
I was wondering if it is possible to get transition effects with it like with [Boron](http://madscript.com/boron/)
Thank you!

**Comment by marcio** [comment]
Hi @Ajar-Ajar, my mindset is keep react-skylight very simple and with no dependencies, but I'll think about that.

Thanks.

**Comment by Ajar-Ajar** [comment]
hey @marcio thank you for your response. let me just say that no dependencies != no transitions...    
At the end of the day, this is a UI component and as such the user experience takes a higher priority then the developer experience (which is great!) so while the user does not seem to care or know about the brilliant code architecture behind the scenes, they do care, a lot about how smooth and slik their experience is. Transitions by now are an expected norm. so if you came so far, the final touches of transitions will create a big difference. I went through all of the react modal components and they always lack either the UX or the es6 well written architecture, so this can fill in the gap... my 2 cents.

**Comment by digitalmaster** [comment]
@Ajar-Ajar I couldn't agree more. Transitions are a must today. In fact that's the only reason I decided to checkout this modal implementation; specifically to see how you've solved the react modal transition issue. 

I also see why @marcio decided to punt transitions; in all the react modal solutions i've seen transitions is where code goes from being beautiful to swipe left 😆  But unfortunately for a modal component this absolutely necessary.

**Comment by snakeyak** [comment]
Agreed to this. @marcio , do you have any current plans to implement them?

**Comment by marcio** [comment]
v0.5.0.
