### ISSUE TITLE
Polyfill Object.assign() if not available (currently affects IE11)

### ISSUE THREAD

**Issue by drywolf** [marcio/react-skylight#36]
Hi, I'm running react-skylight in my app and am testing it now across browsers.

I found that react-skylight depends on [Object.assign() in the skylightstateless.jsx] (https://github.com/marcio/react-skylight/blob/master/src/skylightstateless.jsx#L19) code, which crashes in IE11 because [Object.assign()](http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign) is not yet available in the browser.

For now I worked around this issue by introducing a polyfill into my app, but there really should be a proper fail-safe handling in react-skylight that either throws an error to inform the developer that they need to introduce a polyfill when using react-skylight, or react-skylight could include it's own polyfill to fall back to if it is not natively supported by the browser it is running in.

(for example the [Mozilla polyfill code](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) could be used)

Regards,
Wolfgang

**Comment by marcio** [comment]
Hi @drywolf 

Thanks for your feedback, I'll work in issue soon.

Regards!

**Comment by khanghoang** [comment]
@marcio i just made PR for it, please review
