### ISSUE TITLE
Add classname to override styles

### ISSUE THREAD

**Issue by oyeanuj** [marcio/react-skylight#38]
Hi, thanks for your work on this component! I was wondering if it is possible to pass in a classname that gets passed to the modal window and the overlay? I was hoping to do this as an alternative to inline styles since I am using CSS Modules.

Thanks so much!

**Comment by marcio** [comment]
Hi @oyeanuj!

This improvement is on my enhancements list. Soon I'll work in this.

**Comment by marcosideame** [comment]
Hi @marcio 

Is this feature implemented?
