### ISSUE TITLE
Rename `lib/skylight.js as `lib/skylight.jsx`?

### ISSUE THREAD

**Issue by bebraw** [marcio/react-skylight#4]
Would it be possible for you to rename `lib/skylight.js as `lib/skylight.jsx`?

Webpack can't pick up the right format now and you have to point directly to the file so you get an ugly import like this `require('jsx!react-skylight/src/skylight.js').SkyLight`. I think that could be just `require('react-skylight')` if it was correct.

**Comment by marcio** [comment]
Hi @bebraw, 

The version 0.1.4 has changed skylight.js to skylight.jsx and the namespace was adjusted too.
