### ISSUE TITLE
Large content doesn't scroll...

### ISSUE THREAD

**Issue by tracker1** [marcio/react-skylight#40]
Would be nice if this were configured so that if the modal size exceeds screen size, that the modal area will scroll...  It's a work in progress (almost done if I can find the time), but you can look at how I did this in my [md-datepicker](https://github.com/tracker1/md-datepicker) [demo](http://tracker1.github.io/md-datepicker/).

Basically, I had to place a container inside the overlay with automatic scrolling, so that when the size of the window is smaller than the modal, the modal area becomes scrollable.  If you look at the [stylesheet](https://github.com/tracker1/md-datepicker/blob/master/_src/DatePickerModal/feature/main/style.scss) specifically .outer, .inner, .inner2 is how this is done... it will middle-align the content, unless it's too big, which will be at the top, then scroll.

You'll have to [capture click bubbling from the modal](https://github.com/tracker1/md-datepicker/blob/master/_src/DatePickerModal/feature/main/index.js#L42), in order to prevent the outer from being clicked, doing it the way I did... other than that, it works pretty well.

**Comment by marcio** [comment]
Hi @tracker1!

For simplicity and maintenance reasons I think behaviours like this should be controlled by content owner.

Example: 

```js
<SkyLight ref='modal'>
  <div className='inner-large-content'>
    large content here
  </div>
</SkyLight>
```

In this case you are free to define the best way to show and control content ('inner-large-content'), exactly as you want.

I use this approach in my projects.

**Comment by tracker1** [comment]
Your suggestion won't work, as the scrolling would be inside the modal, not at the outer level... also, it wouldn't resolve the background page scrolling issue...
