### ISSUE TITLE
Warning 'h2' tag

### ISSUE THREAD

**Issue by will88** [marcio/react-skylight#41]
![screen shot](https://cloud.githubusercontent.com/assets/2444888/16339601/d976934a-3a23-11e6-86ea-b00a6f05a268.png)

Is there any way in order to avoid this warning?

Thanks

**Comment by marcio** [comment]
Hi @will88!

Are you using default styles?

**Comment by will88** [comment]
Hi, 

Nope, I'm using a customised style

**Comment by marcio** [comment]
Try change zero values in your styles to: '0px'.

**Comment by will88** [comment]
Yeah it worked! 

Thanks
