### ISSUE TITLE
Multiple Modals on Same Page

### ISSUE THREAD

**Issue by lsbyerley** [marcio/react-skylight#46]
Hello. I've been looking to implement skylight in one of my projects and have run into a couple questions. I have multiple items on a page that when clicked open up a modal with more info. I'm having trouble figuring out how to reference each individual modal when an item is clicked. In your examples, you open them using this.refs.refName.open(). Is there a way to open a modal using an ID? I was hoping to pass an ID to the store (flux), and then use this id to open the appropriate modal.

**Comment by marcio** [comment]
Hi, 

You don't need an id, the 'refName' is a variable.

[https://facebook.github.io/react/docs/more-about-refs.html](https://facebook.github.io/react/docs/more-about-refs.html)
