### ISSUE TITLE
Option to hide title and closebox

### ISSUE THREAD

**Issue by pentool** [marcio/react-skylight#49]
Would be nice if there would be built-in options to hide the dialog title and the closebox. I am implementing my own title and closebox (which is located at the bottom) and so currently I have to specify a CSS override to hide these elements.

Having an option in the 'dialogstyles' or somewhere else to hide these elements would be helpful.

**Comment by vibhas77** [comment]
Hey,

Please let me know how to switch off the title. I tried passing down null as title but it's still rendering a empty h2 tag which has some css affecting my dialog contents.

**Comment by vibhas77** [comment]
Hey,

It was done. To hide title just pass prop titleStyle={{ display: 'none' }} into the skylight component.

**Comment by marcio** [comment]
v0.5.0 fix title option.
