### ISSUE TITLE
Publish compiled version of JSX code

### ISSUE THREAD

**Issue by KyleAMathews** [marcio/react-skylight#5]
As it's then universally consumable.

You could do something similar to https://github.com/andreypopp/react-time/pull/9

**Comment by marcio** [comment]
Hi @KyleAMathews thanks for your comment. In this moment I'm working in some improvements and a new version of skylight is coming soon, your suggestion will be considered.

**Comment by KyleAMathews** [comment]
sounds great!

**Comment by frequencydesign** [comment]
Thanks, this would save me an error.
