### ISSUE TITLE
Callbacks with parameters + Specific callbacks on buttons ?

### ISSUE THREAD

**Issue by elroyK** [marcio/react-skylight#53]
Hi,

I recently started using your skylight component since it's so great and does exactly what I want, but the problem is that it seems to be impossible to give params to callbacks, when they have a parameter the callback functions only run once.

Also, is there a way to specify the callback (or its parameters) to the button that calls the Skylight Modal

Thanks :)

**Comment by marcio** [comment]
Hi!

Can you show some code example that you are trying?

**Comment by elroyK** [comment]
<SkyLight hideOnOverlayClicked dialogStyles={removeItemPopupStyle} ref="popupRemoveItem" id="empty-list-popup" className="popup">
        <h1>Retirer de la liste ?</h1>
            <div id="confirm-buttons">
                <a href="#">
                    <img src="./assets/images/dark-red/confirm-button.svg"/>
                </a>
            </div>
    </SkyLight>

This is called by clicking on an X next to any element in a list. I needed to know which element was clicked so I had a callback function `beforeOpen` update a global var to the id of said element. Since it didn't work more than once, I tried just printing said ID in the console, but it didn't work more than once either. It printed the parameter once in the console upon opening the SkyLight the first time, but then it did nothing. The only way to get it to run every time was to have no parameters to the callback function at all (not evening empty parentheses)

**Comment by marcio** [comment]
Hi!

I think you are inside a loop, and item is one value in your list, ok? If is it, you can pass your item as param to a proxy/bridge function see example: 

```jsx
<li value='${item}'>Tomates <a href="#"><i className="fa fa-times remove-item" aria-hidden="true" onClick={() => this._showDeleteModal(item)}></i></a></li>
```
The show delete modal method:

```jsx
_showDeleteModal(item) {
  //set item in context, ex:
  itemInContext = item;
  //then, open modal
   this.refs.popupRemoveItem.show();
}
```

And you can remove callback beforeOpen because _**itemInContext**_ is already set.

Let me know if it worked.
