### ISSUE TITLE
SkyLightStateless not working

### ISSUE THREAD

**Issue by noushad-pp** [marcio/react-skylight#55]
My SkyLightStatelessComponent is  not showing even when the isVisible prop is set to true.
When debugging with react dev tools i could see that the isVisible prop of SkyLightStatelesscomponent changes but its isVisible state is not set accordingly.
My code
```
<SkyLightStateless isVisible={this.props.page_details.user_popup_requested} dialogStyles={myBigGreenDialog} onCloseClicked={() => {this.closePopUp()}}>
          <Loader loaded={this.props.page_details.popup_user_loaded}/>
          <If condition={this.props.page_details.popup_user_loaded}>
	        <UserPopupCard />
	  </If>
 </SkyLightStateless>
```
(https://cloud.githubusercontent.com/assets/15194796/22596077/27c6b2f0-ea50-11e6-9cfe-7ce3c689d82c.png)

**Comment by townmulti** [comment]
SkyLightStateless also throwing these warnings in the console.

`Warning: Unsupported style property margin-top. Did you mean marginTop? Check the render method of SkyLightStateless.`
`Warning: Unsupported style property margin-left. Did you mean marginLeft? Check the render method of SkyLightStateless.`
`Warning: Unsupported style property margin-bottom. Did you mean marginBottom? Check the render method of SkyLightStateless.`
`Warning: Unsupported style property padding-bottom. Did you mean paddingBottom? Check the render method of SkyLightStateless.`
