### ISSUE TITLE
SkyLightStateless callbacks (afterClose, afterOpen etc.) don't work

### ISSUE THREAD

**Issue by olegzhermal** [marcio/react-skylight#56]
Having SkyLight modal which should be opened when isVisible is true, I'd like do some actions after modal opens (particularly focus on some field). It seems that afterOpen callback does not work (console.log doesn't show anything, when modal opens...)

```
someFunc() {
    console.log('cb test')
}
 
 <SkyLightStateless
    isVisible={isVisible}
    afterOpen={this.someFunc}
 >
....
```

**Comment by townmulti** [comment]
Did you find some solution for this? afterOpen works for me but not afterClose or beforeClose.

**Comment by olegzhermal** [comment]
No. Haven't found any solution. On the moment I submitted the issue, afterOpen did not work. Maybe, they fixed something that it works for you. Have to check again...

**Comment by marcio** [comment]
Hi,

Somebody has an example of this problem? 

For now I'll close this issue, if anyone has an example, please post here and reopen it.

Thanks
