### ISSUE TITLE
Question: what is the preferred why to trigger a popup

### ISSUE THREAD

**Issue by saniko** [marcio/react-skylight#57]
Question: what is the preferred why (SEO wise) to trigger a popup if I cannot use buttons (design issue)?
I need this for site crawlers to crawl our modal content which contains important info.
Any thoughts?

Best.

**Comment by marcio** [comment]
Hi, 

I'm not sure if I understand your question, but you don't need a button, you can show/hide modal in any event. Your app should know the best way to do this. 

Best
