### ISSUE TITLE
use the prop-types package (propTypes deprecated)

### ISSUE THREAD

**Issue by aureliePrd** [marcio/react-skylight#58]
Hi ! Firstable, thank you for react-skylight, it works fine for me !!

Since a few weeks, there is an error for everyone :
"Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead."
The problem is : I installed prop-types but the error is still visible. 

After doing what brianvaughn recommanded, it figured that the problem comes from react-skylight
http://stackoverflow.com/questions/43303761/accessing-proptypes-via-the-main-react-package-is-deprecated

Can you fix it ? 
Thank you again !!

**Comment by marcio** [comment]
Hi, 

New version 0.4.2 fix this issue.
