### ISSUE TITLE
Use fixed positioning instead of absolute for skylight-dialog__overlay?

### ISSUE THREAD

**Issue by bebraw** [marcio/react-skylight#6]
I noticed it can be problematic to have `skylight-dialog__overlay` use absolute positioning by default. If you do this, the overlay won't follow while you are scrolling (it gets 100% width/height based on viewport, not whole document). It might be preferable to use fixed positioning instead. You are already doing this with the dialog itself.

Besides that the modal seems to be performing ok. I have a demo running at http://bebraw.github.io/reactabular/ (hit one of those edit buttons at a row). It could use some styling still.

It could be nice to include some basic animation examples with Skylight. Ie. animate opacity (fade in, fade out).

**Comment by marcio** [comment]
Hi @bebraw, reactabular is pretty good, congratulations!
I'm still working in css/styles, thanks for your feedback and ideas, a new version of skylight is comming soon.
