### ISSUE TITLE
Prop type expects string, but any element works fine

### ISSUE THREAD

**Issue by stahlmanDesign** [marcio/react-skylight#60]
I get the warning: 
```Failed prop type: Invalid prop `title` of type `object` supplied to `SkyLight`, expected `string` ```

I assign my title like this
```
<SkyLight title={<h5>{ myTitle }</h5>} />
```
And it works fine.
Unless I am missing something, I think you can relax the requirement that this be a string to allow any react element.

**Comment by marcio** [comment]
nice idea,

Did on v0.5.0!
