### ISSUE TITLE
Push new version with custom close button

### ISSUE THREAD

**Issue by cobarx** [marcio/react-skylight#64]
Hi, I see there's a commit to add support for a custom close button. We'd like to start using this, however there's no release on npm for it and if I point at HEAD, `lib` hasn't been updated with the new code in `src`. Would it be possible to do an official release?

**Comment by marcio** [comment]
Hi @cobarx, I will release a new version very soon.

**Comment by asifsid88** [comment]
Also while releasing it kindly provide a mechanism to handle unicode character.
`{String.fromCharCode(parseInt('0x00D7', 16))}`
As post minifying the JS, it results into garbage value.

**Comment by JosDalhuisen** [comment]
Hi, is there any news on adding the custom close button?
