### ISSUE TITLE
Support for React 16

### ISSUE THREAD

**Issue by ottoo** [marcio/react-skylight#66]
Add React 16 as a peer dep.

**Comment by ivoilic** [comment]
Ditto. Created a pull request.

**Comment by jacobhixon47** [comment]
Is this going to be fixed? I want to use this modal but I am React ^16.2.0

**Comment by kstratis** [comment]
We definitely need a new release. 

+1 for React 16.2 support

**Comment by imranariffin** [comment]
Anybody working on this? 

Our team is considering to upgrade to 16.2.0 but this is blocking us. It'd be nice if we don't have to find a different modal library.

**Comment by imranariffin** [comment]
Anyone working on the release? Our team is considering to upgrade to React 16.2.0 but this is blocking us.

Would appreciate if someone could spend a little bit time on the release.

**Comment by marcio** [comment]
done! 

v0.5.1 released.
