### ISSUE TITLE
isVisible property does not work (?)

### ISSUE THREAD

**Issue by theweaklink** [marcio/react-skylight#70]
Hi @marcio ,

I just started to use Skylight, it is very nice in many aspects: UI looking, simplicity to call the component and so well documented. So, thank you a lot! 

I just have some troubles with the property `isVisible`. It doesn't seem to be working (or maybe I'm not using it properly). When the property from the store has changed, the property `isVisible` is indeed set to its correct value but the popup does not show up.

I output the component in the console at the time it is render to make sure and we can notice that the **property** `isVisible` is indeed properly changed to `true/false` however the **state** `isVisible` stays always `false` and the popup never shows up.
I made sure of the following:
* If I manually call the `show()` method, the popup shows up as expected.
* when using the `isVisible` property, I made sure I was using `SkyLightStateless` component.

I am missing a parameter or not calling properly?

```
<SkyLightStateless
    dialogStyles={dialog_style}
    hideOnOverlayClicked
    isVisible={dialogVisible}
    onCloseClicked={() => {this.toggleDialogVisibleStore()}}
    ref={ref => this.dialog = ref}
    afterClose={this.updateChart}
    title="My Popup"
>
    Hello
</SkyLightStateless>
```

![isvisibleissue](https://user-images.githubusercontent.com/21156424/39639268-5a3f8b4a-4f8e-11e8-8765-a49ff36fb538.png)

**Comment by marcio** [comment]
Hi,

Skylight works in 2 ways:

First:
```jsx
<SkyLight ref={ref => this.dialog = ref}>...
```
When you need control show/hide directly, like: 
```jsx
this.dialog.show();
this.dialog.hide();
```

The other way is to use in a Stateless scene, and you dont need (shouldn't) call show/hide directly. In this case, use a SkyLightStateless **_without a ref prop_**

```jsx
<SkyLightStateless isVisible={myBoolPropFromStore}>...
```
I hope that helped you.

**Comment by theweaklink** [comment]
thanks @marcio for the super quick response!

For some reason I still don't have any luck with `isVisbile` property on `SkyLightStateless` even after dropping the **ref** prop as suggested. 

On the bright side, using the suggestion of explicit call to `hide/show` does work perfectly. Since they are not triggered by a user event but by the store state, I just needed to put them in the `componentDidUpdate()` method:
```
    componentDidUpdate() {
        if( this.dialog_settings ) {
            const {dialogIsVisible} = this.props.data;
            if( dialogIsVisible ) {
                this.dialog_settings.show();
            } else {
                this.dialog_settings.hide();
            }
        }
    }
```

Thanks a lot for the very helpful suggestions, I'll keep it with a ref then, no problem.
Thanks for providing such a great popup dialog!!

**Comment by marcio** [comment]
Nice workaround @theweaklink.

PS: Can you share the code (store and component) that has problem in the isVisible prop? 
May be a bug in skylight too.

**Comment by theweaklink** [comment]
Hi @marcio ,

the code handling the store state is pretty involving (using saga with redux) and pulls some mechanisms like authentication that would pollute the readability of the code example. So I tried to make a code snippet into `codesandbox` and of course it works very nicely there :) => which means it is not a bug in skylight and there is something happening on my end when the props update events are dispatched. 

So I'll close this issue as it's not a problem in skylight. Using `ref` is actually even better as I am able to get more control over the component.

Thanks a lot for your help and the nice skylight dialog
cheers!
