### ISSUE TITLE
Does not allow to follow ESLint

### ISSUE THREAD

**Issue by OZZlE** [marcio/react-skylight#72]
<SkyLight ref={ref => this.simpleDialog = ref}>

Gives:

    99:18  error  Arrow function should not return assignment  no-return-assign

=> https://eslint.org/docs/rules/no-return-assign

**Comment by marcio** [comment]
Hi,

It's not a skylight problem, if you are using this eslint rule, of course that you should change your syntax to compliance with it.

Most likely ```<SkyLight ref={(ref) => { this.simpleDialog = ref}}>``` will works fou you.

:smile_cat:

**Comment by OZZlE** [comment]
Thank you @marcio ! Although I'm not sure that using ref's for this is the best approach though?

Could it not have a prop `isOpen` that you could send in `true` or `false` to, so whatever button you have to trigger it open updates a state which is sent in as a prop to trigger it open? :)

**Comment by marcio** [comment]
Hi!

It had! In the doc site has an example of a Stateless Modal.

```<SkyLightStateless
          isVisible={myBoolPropFromStore}
          onCloseClicked={() => {actionThatChangesMyBoolPropOnStoreToFalse()}}
          title="A Stateless Modal"
        >
          I'm a Stateless modal!
        </SkyLightStateless>```

Show more at http://marcio.github.io/react-skylight/

**Comment by OZZlE** [comment]
@marcio Sorry man.. I need to rtfm :D My college implemented the popup and created linting errors.. so I was trying to fix them.. Maybe this should be the first example, personally I think it's a better approach 👼
