### ISSUE TITLE
SkylightStateless hideOnOverlayClicked

### ISSUE THREAD

**Issue by OZZlE** [marcio/react-skylight#76]
<SkyLightStateless hideOnOverlayClicked />

Doesn't work..

**Comment by OZZlE** [comment]
I guess it doesn't make sense if it's stateless.. I was more looking for a version that does close when you click the overlay or x-button but which you don't need to use refs, I added own event handlers to close on these events, perhaps it's the way to go? (don't know)

I used a combination of prop and state to handle opening and closing of my wrapper popup component but it was a bit tricky/messy..

**Comment by raindecastro** [comment]
Not sure if this will be helpful but what I did here is I used the prop onOverlayClicked where it dispatches and action from the store to hide the skylight
