### ISSUE TITLE
Loosen peer dependency to allow usage with 0.13 and further?

### ISSUE THREAD

**Issue by bebraw** [marcio/react-skylight#8]
Now it's `"react": "^0.12.x"` which seems a bit too tight. `"react": ">=0.12.0 <1.0.0"` would work though you can use something else if you want.

**Comment by marcio** [comment]
Hi @bebraw, a new version of skylight was published. Your suggestion was accepted. 

And no more css is needed. See the readme for more details.

**Comment by bebraw** [comment]
@marcio Awesome! Thanks.

Is it possible to animate show/hide process? I would like to apply some fading there. Maybe https://facebook.github.io/react/docs/animation.html would work.

**Comment by marcio** [comment]
Yes it is @bebraw !

Work in animations is in the plans.
