### ISSUE TITLE
Allow dialog to be closed by clicking the background

### ISSUE THREAD

**Issue by bebraw** [marcio/react-skylight#9]
Instead of growing the API, maybe it would make sense to make background replaceable? You can provide some default thinger for it. I mean something like:

```javascript
<SkyLight background={<SkyLight.Background onClick={...} />} />
```

If background is not provided, it would use the default implementation.

This injection mechanism could be used for other parts of the component if you want to provide extension points.

Maybe some kind of an alternative API could work for this. It's just the obvious solution that came to my mind.

**Comment by tugend** [comment]
That would be a nice feature. =P

**Comment by marcio** [comment]
Porting react-skylight to es2015.
